In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_excel('https://storage.googleapis.com/sa_via_data/BusOnTimePerformance.xlsx')

In [8]:
df

,ServiceDateTime,Route,RouteName,EarlyDeparture,OnTime,LateArrival,Missing,TimePointCount,OTP,AverageDwellTime
0,2018-01-01,2,BLANCO,23,373,65,59,461,80.91,112.401956
1,2018-01-01,3,SAN PEDRO SKIP,7,358,29,12,394,90.86,175.873310
2,2018-01-01,4,SAN PEDRO Frequent,8,379,5,103,392,96.68,94.193649
3,2018-01-01,5,McCULLOUGH,2,245,16,42,263,93.16,137.789003
4,2018-01-01,8,N ST MARYS,25,226,31,6,282,80.14,107.157249
...,...,...,...,...,...,...,...,...,...,...
35326,2019-01-30,647,North Star / Harry Wurzbach,3,142,6,2,151,94.04,101.236417
35327,2019-01-30,648,North Star / Stone Oak,7,211,7,7,225,93.78,137.306123
35328,2019-01-30,651,Deco District / Castle Hills,4,147,12,2,163,90.18,178.834171
35329,2019-01-30,660,NW Vista College / University P&R,4,99,55,28,158,62.66,87.876620
35330,2019-01-30,672,TAMUSA / Madla Transit Center,7,193,24,7,224,86.16,215.584702